# Generated by Django 4.1.1 on 2023-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(
                null=True,
                blank=True,
            ),
            preserve_default=False,
        ),
    ]
