# Generated by Django 4.1.1 on 2023-01-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_petstagramuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='profile_picture',
            field=models.URLField(blank=True, default=False, null=True),
        ),
    ]
